@startuml
'https://plantuml.com/use-case-diagram
skinparam actorStyle Hollow
skinparam packageStyle rectangle
left to right direction
actor Studerende as stu
actor Underviser as und
actor Sekretær as sek
rectangle BestBooking {
    usecase "Booker lokaler i systemet" as UC1
    usecase "Skema oversigt" as UC2
    usecase "Kalenderoversigt med ledige og optagede lokaler" as UC3
    usecase "Dobbelttjekker skema" as UC4
    usecase "Offentliggørelse af skema" as UC5
}
note right of UC3 : Rød = Optaget, Grøn = Ledig, Grå = tilhørende anden undervisningskategori

actor Underviser as u
actor Sekretær as b
    usecase "Forespørgsel til kursusændring" as u2

u --> (u2)



stu --> (UC2) #blue;line.dotted;text:blue
und --> (UC3) #line:red;line.bold;text:red
und --> (UC1) #line:red;line.bold;text:red
sek --> (UC4) #green;line.dashed;text:green
sek --> (UC5) #green;line.dashed;text:green



@enduml